In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math


# Exercise 00 - Sigmoid

In [221]:
def sigmoid_(x):
    x = np.asarray(x)
    sigm = 1. / (1. + np.exp(-x))
    return sigm

In [222]:
print(sigmoid_(-4))
print(sigmoid_(2))
print(sigmoid_([-4, 2, 0]))

0.01798620996209156
0.8807970779778823
[0.01798621 0.88079708 0.5       ]


In [4]:
# Exercise 01 - Logistic Loss Function

In [33]:
def log_loss_(y_true, y_pred, m, eps=1e-15):
    log_loss = 0.0
    y_true = np.array(y_true).reshape(-1, 1)
    y_pred = np.array(y_pred).reshape(-1, 1)
    for i in range(len(y_pred)):
        log_loss += y_true[i] * math.log(y_pred[i]) + (1 - y_true[i]) * math.log(1 - y_pred[i])
    return(-log_loss / len(y_true))

In [34]:
# Test n.1
x = 4
y_true = 1
theta = 0.5
y_pred = sigmoid_(x * theta)
m = 1 # length of y_true is 1
print(log_loss_(y_true, y_pred, m))
# 0.12692801104297152
# Test n.2
x = [1, 2, 3, 4]
y_true = 0
theta = [-1.5, 2.3, 1.4, 0.7]
x_dot_theta = sum([a*b for a, b in zip(x, theta)])
y_pred = sigmoid_(x_dot_theta)
m = 1
print(log_loss_(y_true, y_pred, m))
# 10.100041078687479
# Test n.3
x_new = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
y_true = [1, 0, 1]
theta = [-1.5, 2.3, 1.4, 0.7]
x_dot_theta = []
for i in range(len(x_new)):
    my_sum = 0
    for j in range(len(x_new[i])):
        my_sum += x_new[i][j] * theta[j]
    x_dot_theta.append(my_sum)
y_pred = sigmoid_(x_dot_theta)
m = len(y_true)
print(log_loss_(y_true, y_pred, m))

[0.12692801]
[10.10004108]
[7.23334703]


# Exercise 02 - Logistic Gradient

In [7]:
def dot(x, y):
    dot = 0.0
    if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim > 2:
        print('Dot Error : x dim')
        return None
    if not isinstance(y, np.ndarray) or y.size == 0 or y.ndim > 2:
        print('Dot Error : y dim')
        return None
    if x.ndim != y.ndim:
        print('Dot Error : incompatible x and y dim')
        return None
    #x_t = x.reshape(-1, 1)
    for elem in range(x.size):
        dot += x[elem] * y[elem]
    return dot

In [45]:
def log_gradient_(x, y_true, y_pred):
    
#     try:
    grad = np.empty(0)
    for item in x:
#         print(item)
#         print(y_pred - y_true)
        grad = np.append(grad, np.array(y_pred - y_true).reshape(-1, 1) * np.array(item))
#     except :
#         grad = dot(np.array((y_pred - y_true)).reshape(-1, 1), np.array(x))
    return (grad)

In [46]:
# Test n.1
x = [1, 4.2] # 1 represent the intercept
y_true = 1
theta = [0.5, -0.5]
x_dot_theta = sum([a*b for a, b in zip(x, theta)])
y_pred = sigmoid_(x_dot_theta)
print(log_gradient_(x, y_pred, y_true))
# [0.8320183851339245, 3.494477217562483]
print("\n")
# Test n.2
x = [1, -0.5, 2.3, -1.5, 3.2]
y_true = 0
theta = [0.5, -0.5, 1.2, -1.2, 2.3]
x_dot_theta = sum([a*b for a, b in zip(x, theta)])
y_pred = sigmoid_(x_dot_theta)
print(log_gradient_(x, y_true, y_pred))
# [0.99999685596372, -0.49999842798186, 2.299992768716556, -1.4999952839455801, 3.1999899390839044]
print("\n")

# Test n.3
x_new = [[1, 2, 3, 4, 5], [1, 6, 7, 8, 9], [1, 10, 11, 12, 13]]
# first column of x_new are intercept values initialized to 1
y_true = [1, 0, 1]
theta = [0.5, -0.5, 1.2, -1.2, 2.3]
x_new_dot_theta = []
for i in range(len(x_new)):
    my_sum = 0
    for j in range(len(x_new[i])):
        my_sum += x_new[i][j] * theta[j]
    x_new_dot_theta.append(my_sum)
y_pred = sigmoid_(x_new_dot_theta)
print(log_gradient_(x_new, y_true, y_pred))
# [0.9999445100449934, 5.999888854245219, 6.999833364290213, 7.999777874335206, 8.999722384380199

[0.83201839 3.49447722]


[ 0.99999686 -0.49999843  2.29999277 -1.49999528  3.19998994]


[-5.54485247e-05 -1.10897049e-04 -1.66345574e-04 -2.21794099e-04
 -2.77242624e-04  9.99999959e-01  1.99999992e+00  2.99999988e+00
  3.99999983e+00  4.99999979e+00 -3.09081649e-11 -6.18163298e-11
 -9.27244947e-11 -1.23632660e-10 -1.54540825e-10 -5.54485247e-05
 -3.32691148e-04 -3.88139673e-04 -4.43588198e-04 -4.99036723e-04
  9.99999959e-01  5.99999975e+00  6.99999971e+00  7.99999967e+00
  8.99999963e+00 -3.09081649e-11 -1.85448989e-10 -2.16357154e-10
 -2.47265319e-10 -2.78173484e-10 -5.54485247e-05 -5.54485247e-04
 -6.09933772e-04 -6.65382297e-04 -7.20830821e-04  9.99999959e-01
  9.99999959e+00  1.09999995e+01  1.19999995e+01  1.29999995e+01
 -3.09081649e-11 -3.09081649e-10 -3.39989814e-10 -3.70897979e-10
 -4.01806144e-10]


# Exercise 03 - Vectorized Logistic Loss Function

In [225]:
def vec_log_loss_(y_true, y_pred, m, eps=1e-15):
    log_loss = 0.0
    y_true = np.array(y_true).reshape(-1, 1)
    y_pred = np.array(y_pred).reshape(-1, 1)
    for i in range(y_true.size):
        log_loss += (y_true[i] * math.log(y_pred[i])) + ((1 - y_true[i]) * math.log(1 - y_pred[i]))
    return(log_loss / -m)

In [226]:
x = 4
y_true = 1
theta = 0.5
y_pred = sigmoid_(x * theta)
m = 1 # length of y_true is 1
print(vec_log_loss_(y_true, y_pred, m))

x = np.array([1, 2, 3, 4])
y_true = 0
theta = np.array([-1.5, 2.3, 1.4, 0.7])
y_pred = sigmoid_(np.dot(x, theta))
m = 1
print(vec_log_loss_(y_true, y_pred, m))

x_new = np.arange(1, 13).reshape((3, 4))
y_true = np.array([1, 0, 1])
theta = np.array([-1.5, 2.3, 1.4, 0.7])
y_pred = sigmoid_(np.dot(x_new, theta))
m = len(y_true)
print(vec_log_loss_(y_true, y_pred, m)) 

[0.12692801]
[10.10004108]
[7.23334703]


# Exercise 04 - Vectorized Logistic Gradient

In [12]:
def dot(x, y):
    dot = 0.0
    if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim > 2:
        print('Dot Error : x dim')
        return None
    if not isinstance(y, np.ndarray) or y.size == 0 or y.ndim > 2:
        print('Dot Error : y dim')
        return None
    if x.ndim != y.ndim:
        print('Dot Error : incompatible x and y dim')
        return None
    for elem in range(x.size):
        dot += x[elem] * y[elem]
    return dot

In [214]:
def vec_log_gradient_(x, y_true, y_pred):
    Y = (y_pred - y_true).reshape(-1, 1)
    if x.ndim != 2:
        x = np.array([x])
    return (dot((y_pred - y_true).reshape(-1, 1), x))

In [215]:
# Test n.1
x = np.array([1, 4.2]) # x[0] represent the intercept
y_true = 1
theta = np.array([0.5, -0.5])
y_pred = sigmoid_(np.dot(x, theta))
print(vec_log_gradient_(x, y_pred, y_true))
# [0.83201839 3.49447722]
print()


# Test n.2
x = np.array([1, -0.5, 2.3, -1.5, 3.2]) # x[0] represent the intercept
y_true = 0
theta = np.array([0.5, -0.5, 1.2, -1.2, 2.3])
y_pred = sigmoid_(np.dot(x, theta))
print(vec_log_gradient_(x, y_true, y_pred))
# [ 0.99999686 -0.49999843 2.29999277 -1.49999528 3.19998994]
print()

# Test n.3
x_new = np.arange(2, 14).reshape((3, 4))
x_new = np.insert(x_new, 0, 1, axis=1)
# first column of x_new are now intercept values initialized to 1
y_true = np.array([1, 0, 1])
theta = np.array([0.5, -0.5, 1.2, -1.2, 2.3])
y_pred = sigmoid_(np.dot(x_new, theta))
print(vec_log_gradient_(x_new, y_true, y_pred))
# [0.99994451 5.99988885 6.99983336 7.99977787 8.99972238]

[0.83201839 3.49447722]

[ 0.99999686 -0.49999843  2.29999277 -1.49999528  3.19998994]

[0.99994451 5.99988885 6.99983336 7.99977787 8.99972238]


# Exercise 05 - Logistic Regression

In [216]:
df_train = pd.read_csv('../subjects/day02/resources/dataset/train_dataset_clean.csv', delimiter=',', header=None, index_col=False)
df_test = pd.read_csv('../subjects/day02/resources/dataset/test_dataset_clean.csv', delimiter=',', header=None, index_col=False)

x_train, y_train = np.array(df_train.iloc[:, 1:82]), df_train.iloc[:, 0]
x_test, y_test = np.array(df_test.iloc[:, 1:82]), df_test.iloc[:, 0]

In [259]:
class LogisticRegressionBatchGd:
    def __init__(self, alpha=0.001, max_iter=1000, verbose=False, learning_rate='constant'):
        self.alpha = alpha
        self.max_iter = max_iter
        self.verbose = verbose
        self.learning_rate = learning_rate # can be 'constant' or 'invscaling'
        self.thetas = []
        
    def fit(self, x_train, y_train):
        y_pred = self.predict(x_train)
        X_train = np.concatenate((np.ones((x_train.shape[0],1)), x_train), axis=1)
        for i in range(self.max_iter):
#             if i % 150 == 0:
#                 loss = self.loss_(x_train, y_train)
#                 print("epoch =", i,"  loss = ", loss)
#             print(self.__vec_log_gradient_(x_train, y_train, y_pred))
#             print(_vec_log_gradient(x_train, y_train, y_pred))
#             self.thetas -= self.alpha / m * gradient
            self.thetas = self.thetas - self.alpha * vec_log_gradient_(X_train, np.array(y_train).reshape(-1, 1), y_pred)
        return(self.thetas)
    def predict(self, x_train):
        if not np.array(self.thetas).any():
            self.thetas = np.ones(x_train.shape[1] + 1)
        X_conc = np.concatenate((np.ones((x_train.shape[0],1)), x_train), axis=1)
        pred = np.empty(0)
        for j in range(X_conc.shape[0]):
            pred = np.append(pred, sigmoid_(dot(self.thetas, X_conc[j])))
        return (pred.reshape(-1, 1))
    
    def __vec_log_gradient_(self, x, y_true, y_pred):
        X = np.array(x)
        y_t, y_p = np.array(y_true), np.array(y_pred)
        # gradient = np.dot(X.T, (y_p - y_t)) / y_t.shape[0]
        # gradient = ((y_p - y_t) * X.T) / X.shape[0]
        gradient = np.dot((y_p - y_t), X)
        return gradient
    
    def score(self, x_train, y_train):
        y_pred = (self.predict(x_train) >= 0.5).astype(int)
        y_pred = y_pred.flatten()
        accuracy = np.mean(y_pred == y_train)
        return accuracy * 100

    def loss_(self, x_train, y_train, eps=1e-15):
        y_pred = self.predict(x_train)
        m = y_pred.shape[0]
        log_loss = 0.0
        y_true = np.array(y_train).reshape(-1, 1)
        y_pred = np.array(y_pred).reshape(-1, 1)
        for i in range(y_true.size):
            log_loss += (y_true[i] * math.log(y_pred[i])) + ((1 - y_true[i]) * math.log(1 - y_pred[i]))
        return(log_loss / -m)

In [260]:
model = LogisticRegressionBatchGd(alpha=0.01, max_iter=1)

In [261]:
model.fit(x_train, y_train)

array([-2.15585864e+02,  1.84659255e+01,  2.59035060e+01,  2.82351692e+01,
        1.54345252e+01,  1.33920495e+01, -1.60375189e+01, -1.30808358e+01,
       -7.90181846e+00, -3.67921392e+00, -4.67059308e+00,  8.68593898e-01,
        9.59440000e-01, -8.91170942e+01, -3.78307159e+01, -8.18714606e+00,
       -7.87994950e+00, -2.67823750e+00,  8.85505303e-01, -2.57157691e+01,
       -1.86426500e+01, -2.96983829e+01, -2.26622694e+01, -2.65642456e+01,
       -1.39883843e+01, -9.93555573e+00, -9.38946282e+00, -6.81378735e+00,
       -4.93679091e+00, -3.01335983e+00, -3.51289513e-01,  9.26849497e-01,
       -7.02046129e+01, -4.04477291e+01, -3.02231826e+01, -6.40532129e+00,
       -7.46859401e+00, -2.49758623e+01, -6.33539057e+00, -1.57980026e+00,
       -1.26444204e+00, -8.91558340e+01, -3.75529819e+00, -3.23494694e-01,
        1.18196282e-01,  3.50104084e-02,  2.29251599e-01,  1.98278960e-01,
        4.18886220e-01,  3.46279949e-01,  4.34391133e-01,  4.69160313e-01,
        3.75443822e-01,  

In [262]:
model.predict(x_train)

array([[1.05602164e-166],
       [4.20544708e-106],
       [7.24569932e-154],
       ...,
       [2.81924866e-159],
       [7.27691827e-191],
       [6.88901948e-121]])

In [283]:
class LogisticRegressionBatchGd:
    def __init__(self, alpha=0.001, max_iter=1000, verbose=False, learning_rate='constant'):
        self.alpha = alpha
        self.max_iter = max_iter
        self.verbose = verbose
        self.learning_rate = learning_rate # can be 'constant' or 'invscaling'
        self.thetas = []
        self.threshold = .5

    def fit(self, x_train, y_train):
        m, n = x_train.shape[:2]
        self.thetas = np.zeros(n)
        gap = int(self.max_iter / 10)
        for i in range(self.max_iter):
            y_pred = self.__sigmoid_(np.dot(x_train, self.thetas))
            self.thetas -= self.alpha / m * self.__vec_log_gradient_(x_train, y_train, y_pred)

            if self.verbose and i % 150 == 0:
                y_pred = self.__sigmoid_(np.dot(x_train, self.thetas))
                print(f'epoch: {i} loss: {self.__vec_log_loss_(y_train, y_pred, y_train.shape[0])} \t')
        return self

    def predict(self, x_train):
        return self.__sigmoid_(np.dot(x_train, self.thetas)) >= self.threshold

    def score(self, x_train, y_train):
        return (self.predict(x_train) == y_train).mean()

    def __sigmoid_(self, x):
        x = np.asarray(x)
        sigm = 1. / (1. + np.exp(-x))
        return sigm

    def __vec_log_gradient_(self, x, y_true, y_pred):
        X = np.array(x)
        y_t, y_p = np.array(y_true), np.array(y_pred)
        gradient = np.dot((y_p - y_t), X)
        return gradient

    def __vec_log_loss_(self, y_true, y_pred, m, eps=1e-15):
        y_t, y_p = np.array(y_true), np.array(y_pred)
        cost = (1 / m) * (((-y_t).T * np.log(y_p + eps)) - ((1 - y_t).T * np.log(1 - y_p + eps)))
        return cost if isinstance(cost, float) else cost.sum()


In [284]:
model = LogisticRegressionBatchGd(alpha=0.01, max_iter=1500, verbose=True)

In [285]:
model.fit(x_train, y_train)

epoch: 0 loss: 0.6919184362942151 	
epoch: 150 loss: 0.5664406156483319 	
epoch: 300 loss: 0.5038371783940814 	
epoch: 450 loss: 0.46685696168771085 	
epoch: 600 loss: 0.4424623865617848 	
epoch: 750 loss: 0.4251654907630811 	
epoch: 900 loss: 0.4122715670402301 	
epoch: 1050 loss: 0.4022999198252241 	
epoch: 1200 loss: 0.3943668357591168 	
epoch: 1350 loss: 0.38791103922603876 	


In [286]:
print(f'Score on train dataset : {model.score(x_train, y_train)}')
y_pred = model.predict(x_test)
print(f'Score on test dataset : {(y_pred == y_test).mean()}')

Score on train dataset : 0.831669789011394
Score on test dataset : 0.8328726736686936


# Exercise 06 - Accuracy

In [304]:
from sklearn.metrics import accuracy_score

def accuracy_score_(y_true, y_pred):
    return ((y_pred == y_true).mean())

In [305]:
# Test n.1
y_pred = np.array([1, 1, 0, 1, 0, 0, 1, 1])
y_true = np.array([1, 0, 0, 1, 0, 1, 0, 0])
print(accuracy_score_(y_true, y_pred))
# print(accuracy_score(y_true, y_pred))
# 0.5


# Test n.2
y_pred = np.array(['norminet', 'dog', 'norminet', 'norminet', 'dog', 'dog', 'dog', 'dog'])
y_true = np.array(['dog', 'dog', 'norminet', 'norminet', 'dog', 'norminet', 'dog', 'norminet'])
print(accuracy_score_(y_true, y_pred))
# print(accuracy_score(y_true, y_pred))
# 0.625

0.5
0.625


# Exercise 07 - Precision

In [402]:
def precision_score_(y_true, y_pred, pos_label=1):
    

In [403]:
# # Test n.1
# y_pred = np.array([1, 1, 0, 1, 0, 0, 1, 1])
# y_true = np.array([1, 0, 0, 1, 0, 1, 0, 0])
# print(precision_score_(y_true, y_pred))
# # print(precision_score(y_true, y_pred))
# # 0.4
# # 0.4

# Test n.2
y_pred = np.array(['norminet', 'dog', 'norminet', 'norminet', 'dog', 'dog', 'dog', 'dog'])
y_true = np.array(['dog', 'dog', 'norminet', 'norminet', 'dog', 'norminet', 'dog', 'norminet'])
print(precision_score_(y_true, y_pred, pos_label='dog'))
# print(precision_score(y_true, y_pred, pos_label='dog'))
# 0.6
# 0.6
# # Test n.3
# print(precision_score_(y_true, y_pred, pos_label='norminet'))
# print(precision_score(y_true, y_pred, pos_label='norminet'))
# 0.6666666666666666
# 0.6666666666666666

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()