In [4]:
import numpy as np
import math

# Exercise 00 - Sum

In [5]:
def sum_(x, f):
	sum = 0.0
	if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim != 1:
		return None
	try :
		f(x[0])
	except :
		return None
	for item in x:
		sum += f(item)
	return sum

# Exercise 01 - Mean

In [6]:
def mean(x):
	mean = 0.0
	if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim != 1:
		return None
	for item in x:
		mean += item
	return mean / x.size

# Exercise 02 - Variance

In [7]:
def variance(x):
    var = 0.0
    x_mean = mean(x)
    for item in x:
        var += (item - x_mean)**2
    return var / x.size

In [8]:
 X = np.array([0, 15, -9, 7, 12, 3, -21])
variance(X)

134.57142857142858

# Exercise 03 - Standard Deviation

In [9]:
def std(x):
    return math.sqrt(variance(x))

In [10]:
 X = np.array([0, 15, -9, 7, 12, 3, -21])
std(X)

11.600492600378166

# Exercise 04 - Dot product

In [11]:
def dot(x, y):
    dot = 0.0
    if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim != 1:
        return None
    if not isinstance(y, np.ndarray) or y.size == 0 or y.ndim != 1:
        return None
    if x.ndim != y.ndim:
        return None
    for elem in range(x.size):
        dot += x[elem] * y[elem]
    return dot
            
    
    

In [12]:
X = np.array([0, 15, -9, 7, 12, 3, -21])
Y = np.array([2, 14, -13, 5, 12, 4, -19])
print(dot(X, Y))
print(np.dot(X, Y))
print(dot(X, X))
print(np.dot(X, X))
print(dot(Y, Y))
print(np.dot(Y, Y))

917.0
917
949.0
949
915.0
915


# Exercise 05 - Matrix-vector product

In [13]:
# def mat_vec_prod(x, y):
#     prod = np.empty(0)
#     for i in range(x.size):
#         prod[i] = x[i] * y
#     print(prod)

def mat_vec_prod(x, y):
    prod = np.empty(0)
    if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim != 2:
        return None
    if not isinstance(y, np.ndarray) or y.size == 0:
        return None
    if x.shape[1] != y.shape[0]:
        return None
    for elem in x:
        prod = np.append(prod, dot(elem, y.ravel()))
    return prod.reshape(-1, 1)

In [14]:
 W = np.array([
 [ -8, 8, -6, 14, 14, -9, -4],
 [ 2, -11, -2, -11, 14, -2, 14],
 [-13, -2, -5, 3, -8, -4, 13],
 [ 2, 13, -14, -15, -14, -15, 13],
 [ 2, -1, 12, 3, -7, -3, -6]])
X = np.array([0, 15, -9, 7, 12, 3, -21]).reshape((7,1))
Y = np.array([2, 14, -13, 5, 12, 4, -19]).reshape((7,1))

mat_vec_prod(W, X)

array([[ 497.],
       [-356.],
       [-345.],
       [-270.],
       [ -69.]])

# Exercise 06 - Matrix-matrix product

In [15]:
def mat_mat_prod(x, y):
    if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim != 2:
        return None
    if not isinstance(y, np.ndarray) or y.size == 0 or x.ndim != 2:
        return None
    if x.shape[1] != y.shape[0]:
        return None
    for j in range(y.shape[1]):
        if j == 0:
            prod = mat_vec_prod(x, y[:,j])
        else:
            prod = np.append(prod, mat_vec_prod(x, y[:,j]), axis=1)
    return prod
    
W = np.array([
 [ -8, 8, -6, 14, 14, -9, -4],
 [ 2, -11, -2, -11, 14, -2, 14],
 [-13, -2, -5, 3, -8, -4, 13],
 [ 2, 13, -14, -15, -14, -15, 13],
 [ 2, -1, 12, 3, -7, -3, -6]])
Z = np.array([
 [ -6, -1, -8, 7, -8],
 [ 7, 4, 0, -10, -10],
 [ 7, -13, 2, 2, -11],
 [ 3, 14, 7, 7, -4],
 [ -1, -3, -8, -4, -14],
 [ 9, -14, 9, 12, -7],
 [ -9, -4, -10, -3, 6]])

print(mat_mat_prod(W, Z))

[[  45.  414.   -3. -202. -163.]
 [-294. -244. -367.  -79.   62.]
 [-107.  140.   13. -115.  385.]
 [-302.  222. -302. -412.  447.]
 [ 108.  -33.  118.   79.  -67.]]


# Exercise 07 - Mean Squared Error

In [16]:
def mse(y, y_hat):
    mse_ = 0.0
    for i in range(y.size):
        mse_ += (y[i] - y_hat[i])**2
    return mse_ / y.size

In [17]:
X = np.array([0, 15, -9, 7, 12, 3, -21])
Y = np.array([2, 14, -13, 5, 12, 4, -19])
print(mse(X, Y))

4.285714285714286


# Exercise 08 - Vectorized Mean Squared Error

In [18]:
def vec_mse(y, y_hat):
    mse_ = 0.0
    mse_ = (dot((y_hat - y), (y_hat - y))) / y.size
    return mse_

In [19]:
X = np.array([0, 15, -9, 7, 12, 3, -21])
Y = np.array([2, 14, -13, 5, 12, 4, -19])
vec_mse(X, Y)
vec_mse(X, X)

0.0

# Exercise 09 - Mean Squared Error as linear cost function

In [20]:
def linear_mse(x, y, theta):
    mse_ = 0.0
    for i in range(len(x)):
        mse_ += ((dot(theta, x[i])) - y[i])**2
    return(mse_ / len(x))

In [21]:
X = np.array([
 [ -6, -7, -9],
 [ 13, -2, 14],
 [ -7, 14, -1],
 [ -8, -4, 6],
 [ -5, -9, 6],
 [ 1, -5, 11],
 [ 9, -11, 8]])
Y = np.array([2, 14, -13, 5, 12, 4, -19])
Z = np.array([3,0.5,-6])
linear_mse(X, Y, Z)

W = np.array([0,0,0])
linear_mse(X, Y, W)

130.71428571428572

# Exercise 10 - Vectorized Mean Squared Error as a linear cost function

In [22]:
def vec_linear_mse(x, y, theta):
    mse_ = 0.0
    mse_ = mat_mat_prod(((mat_vec_prod(X, theta) - y.reshape(-1, 1)).T),  (mat_vec_prod(X, theta) - y.reshape(-1, 1)))
    return((mse_ / x.shape[0]))[0][0]

In [23]:
X = np.array([
 [ -6, -7, -9],
 [ 13, -2, 14],
 [ -7, 14, -1],
 [ -8, -4, 6],
 [ -5, -9, 6],
 [ 1, -5, 11],
 [ 9, -11, 8]])
Y = np.array([2, 14, -13, 5, 12, 4, -19])
Z = np.array([3,0.5,-6])
vec_linear_mse(X, Y, Z)

2641.0

# Exercise 11 - Linear Gradient - iterative version

In [24]:
def gradient(x, y, theta):
    nabla = 0.0
    for j in range(len(x)):
        nabla += ((dot(theta, x[j])) - y[j]) * x[j]
    return nabla / y.size

In [25]:
X = np.array([
 [ -6, -7, -9],
 [ 13, -2, 14],
 [ -7, 14, -1],
 [ -8, -4, 6],
 [ -5, -9, 6],
 [ 1, -5, 11],
 [ 9, -11, 8]])
Y = np.array([2, 14, -13, 5, 12, 4, -19])
Z = np.array([3,0.5,-6])
gradient(X, Y, Z)
# W = np.array([0,0,0])
# gradient(X, Y, W)
# gradient(X, X.dot(Z), Z)

array([ -37.35714286,  183.14285714, -393.        ])

# Exercise 12 - Linear Gradient - vectorized version

In [375]:
def vec_gradient(x, y, theta):
    nabla = 0.0
    nabla = mat_mat_prod(x.T, (mat_vec_prod(x, theta) - y.reshape(-1, 1)))
    return nabla / y.size

In [377]:
X = np.array([
 [ -6, -7, -9],
 [ 13, -2, 14],
 [ -7, 14, -1],
 [ -8, -4, 6],
 [ -5, -9, 6],
 [ 1, -5, 11],
 [ 9, -11, 8]])
Y = np.array([2, 14, -13, 5, 12, 4, -19])
Z = np.array([3,0.5,-6])
vec_gradient(X, Y.reshape(-1 ,1), Z)

array([[ -37.35714286],
       [ 183.14285714],
       [-393.        ]])